baseURL = "https://noumena-network.github.io/"
languageCode = "en-us"
title = "Noumena Research"
theme = ""

[params]
  description = "Research from Noumena"
  author = "xjdr"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "native"
    noClasses = false
    lineNos = false
    codeFences = true
